# Generated by Django 2.2.4 on 2019-09-02 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptionData',
            fields=[
                ('nome', models.CharField(max_length=200)),
            ],
        ),
    ]
